# Generated by Django 3.2.13 on 2023-09-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('effort', models.CharField(choices=[('L', 'Little'), ('M', 'Medium'), ('B', 'Big')], max_length=1)),
                ('frequency', models.CharField(choices=[('N', 'Never'), ('S', 'Sometimes'), ('A', 'Always')], max_length=1)),
                ('like_rank', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('N', 'Never'), ('S', 'Sometimes'), ('A', 'Always')], max_length=1)),
                ('like_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('num_of_players', models.CharField(max_length=50)),
                ('creation_date', models.DateField(max_length=50)),
                ('like_rank', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
